// NOFX i18n Consolidation - Translation Keys
// Generated by Atlas Orchestrator
// Branch: feat/i18n-consolidation-patch
// Purpose: Centralize scattered i18n strings from 8 strategy components

// ============================================================================
// COIN SOURCE TRANSLATIONS (40 keys)
// ============================================================================
export const coinSource = {
  sourceType: { zh: '数据来源类型', en: 'Source Type', es: 'Tipo de Fuente' },
  static: { zh: '静态列表', en: 'Static List', es: 'Lista Estática' },
  ai500: { zh: '热门币种', en: 'Hot Coins', es: 'Monedas Populares' },
  oi_top: { zh: 'OI 持仓增加', en: 'OI Increase', es: 'Aumento OI' },
  oi_low: { zh: 'OI 持仓减少', en: 'OI Decrease', es: 'Disminución OI' },
  mixed: { zh: '混合模式', en: 'Mixed Mode', es: 'Modo Mixto' },
  market: { zh: '市场数据', en: 'Market', es: 'Mercado' },
  staticCoins: {
    zh: '自定义币种',
    en: 'Custom Coins',
    es: 'Monedas Personalizadas',
  },
  addCoin: { zh: '添加币种', en: 'Add Coin', es: 'Agregar Moneda' },
  useAI500: {
    zh: '启用热门币种筛选',
    en: 'Enable Hot Coin Screening',
    es: 'Habilitar Filtrado',
  },
  ai500Limit: { zh: '数量上限', en: 'Limit', es: 'Límite' },
  useOITop: {
    zh: '启用 OI 持仓增加榜',
    en: 'Enable OI Increase',
    es: 'Habilitar Aumento OI',
  },
  oiTopLimit: { zh: '数量上限', en: 'Limit', es: 'Límite' },
  useOILow: {
    zh: '启用 OI 持仓减少榜',
    en: 'Enable OI Decrease',
    es: 'Habilitar Disminución OI',
  },
  oiLowLimit: { zh: '数量上限', en: 'Limit', es: 'Límite' },
  staticDesc: {
    zh: '手动指定交易币种列表',
    en: 'Manually specify trading coins',
    es: 'Especificar monedas manualmente',
  },
  mixedConfig: {
    zh: '组合数据源配置',
    en: 'Combined Sources Configuration',
    es: 'Configuración Combinada',
  },
  mixedSummary: {
    zh: '已选组合',
    en: 'Selected Sources',
    es: 'Fuentes Seleccionadas',
  },
  maxCoins: { zh: '最多', en: 'Up to', es: 'Hasta' },
  coins: { zh: '个币种', en: 'coins', es: 'monedas' },
  dataSourceConfig: {
    zh: '数据源配置',
    en: 'Data Source Configuration',
    es: 'Configuración de Fuente',
  },
  excludedCoins: {
    zh: '排除币种',
    en: 'Excluded Coins',
    es: 'Monedas Excluidas',
  },
  excludedCoinsDesc: {
    zh: '这些币种将从所有数据源中排除，不会被交易',
    en: 'These coins will be excluded from all sources and will not be traded',
    es: 'Estas monedas serán excluidas de todas las fuentes',
  },
  addExcludedCoin: {
    zh: '添加排除',
    en: 'Add Excluded',
    es: 'Agregar Excluida',
  },
  nofxosNote: {
    zh: 'NofxOS 数据源（可选，需在指标配置中设置 API Key）',
    en: 'NofxOS data source (optional, set API Key in Indicators)',
    es: 'NofxOS (opcional, configurar API Key)',
  },
  ai500Desc: {
    zh: 'NofxOS 热门币种筛选（需 API Key）',
    en: 'NofxOS hot coin screening (requires API Key)',
    es: 'NofxOS filtrado (requiere API Key)',
  },
  oi_topDesc: {
    zh: 'NofxOS OI 增加榜（需 API Key）',
    en: 'NofxOS OI increase (requires API Key)',
    es: 'NofxOS OI creciente (requiere API Key)',
  },
  oi_lowDesc: {
    zh: 'NofxOS OI 减少榜（需 API Key）',
    en: 'NofxOS OI decrease (requires API Key)',
    es: 'NofxOS OI decreciente (requiere API Key)',
  },
  exchangeSource: {
    zh: '数据交易所',
    en: 'Exchange Source',
    es: 'Exchange de Datos',
  },
  exchangeSourceDesc: {
    zh: '选择数据来源交易所',
    en: 'Select exchange for data',
    es: 'Seleccionar exchange',
  },
  legacyNofxos: {
    zh: 'Legacy: NofxOS（可选）',
    en: 'Legacy: NofxOS (Optional)',
    es: 'Legacy: NofxOS (Opcional)',
  },
  legacyNofxosDesc: {
    zh: 'NofxOS 数据源当前不可用，可保留配置待恢复后启用',
    en: 'NofxOS data source currently unavailable, config preserved for future use',
    es: 'NofxOS no disponible actualmente',
  },
  mixedDesc: {
    zh: '组合多种数据源',
    en: 'Combine multiple sources',
    es: 'Combinar fuentes múltiples',
  },
  marketDesc: {
    zh: '从交易所实时获取候选币种（热门/OI增/OI减，支持切换交易所）',
    en: 'Live exchange data: hot coins, OI increase/decrease, switchable exchange',
    es: 'Datos en vivo del exchange: popular/OI, exchange configurable',
  },
  marketConfig: {
    zh: '市场数据配置',
    en: 'Market Source Config',
    es: 'Config. de Mercado',
  },
  marketList: { zh: '榜单类型', en: 'Ranking Type', es: 'Tipo de Ranking' },
  marketListHot: { zh: '热门币种', en: 'Hot Coins', es: 'Monedas Populares' },
  marketListOITop: { zh: 'OI 增加', en: 'OI Increase', es: 'OI Aumento' },
  marketListOILow: { zh: 'OI 减少', en: 'OI Decrease', es: 'OI Disminución' },
  marketLimit: { zh: 'Top N', en: 'Top N', es: 'Top N' },
  oiIncreaseShort: { zh: 'OI增', en: 'OI↑', es: 'OI↑' },
  oiDecreaseShort: { zh: 'OI减', en: 'OI↓', es: 'OI↓' },
  custom: { zh: '自定义', en: 'Custom', es: 'Personalizado' },
  excludedNone: { zh: '无', en: 'None', es: 'Ninguno' },
  oiIncreaseTitle: { zh: 'OI 持仓增加榜', en: 'OI Increase', es: 'OI Aumento' },
  oiDecreaseTitle: {
    zh: 'OI 持仓减少榜',
    en: 'OI Decrease',
    es: 'OI Disminución',
  },
  oiIncreaseLabel: { zh: 'OI 增加', en: 'OI Increase', es: 'OI Aumento' },
  forLong: { zh: '适合做多', en: 'For long', es: 'Para largo' },
  oiDecreaseLabel: { zh: 'OI 减少', en: 'OI Decrease', es: 'OI Disminución' },
  forShort: { zh: '适合做空', en: 'For short', es: 'Para corto' },
}

// ============================================================================
// AI SCREENER TRANSLATIONS
// ============================================================================
export const aiScreener = {
  title: {
    zh: 'AI 智能筛选',
    en: 'AI Smart Screener',
    es: 'Filtro Inteligente AI',
  },
  ai_screener: { zh: 'AI 筛选', en: 'AI Screener', es: 'AI Filtro' },
  desc: {
    zh: '系统AI定时筛选符合条件的币种，保证始终有可用交易标的',
    en: 'System AI periodically screens coins matching criteria, ensuring tradeable assets are always available',
    es: 'AI filtra monedas periódicamente',
  },
  ai_screenerDesc: {
    zh: 'AI定时筛选符合条件的币种',
    en: 'AI periodically screens matching coins',
    es: 'AI filtra monedas periódicamente',
  },
  interval: {
    zh: '筛选间隔',
    en: 'Screening Interval',
    es: 'Intervalo de Filtrado',
  },
  maxCoins: { zh: '最大币种数', en: 'Max Coins', es: 'Máx. Monedas' },
  volumeOiFilters: {
    zh: '成交量与持仓量过滤',
    en: 'Volume & OI Filters',
    es: 'Filtros de Volumen y OI',
  },
  minVolume: {
    zh: '最低24h成交额',
    en: 'Min 24h Volume',
    es: 'Volumen Mín. 24h',
  },
  minOI: { zh: '最低持仓量', en: 'Min Open Interest', es: 'OI Mínimo' },
  priceChangeRange: {
    zh: '24h涨跌幅范围',
    en: '24h Price Change Range',
    es: 'Rango de Cambio 24h',
  },
  sentimentPrefs: {
    zh: '情绪偏好',
    en: 'Sentiment Preferences',
    es: 'Preferencias de Sentimiento',
  },
  preferLong: { zh: '偏好多头', en: 'Prefer Long Bias', es: 'Preferir Largo' },
  preferShort: {
    zh: '偏好空头',
    en: 'Prefer Short Bias',
    es: 'Preferir Corto',
  },
  preferOIGrowth: {
    zh: '偏好OI增长',
    en: 'Prefer OI Growth',
    es: 'Preferir Crecimiento OI',
  },
  preferVolumeGrowth: {
    zh: '偏好成交量增长',
    en: 'Prefer Volume Growth',
    es: 'Preferir Crecimiento Volumen',
  },
  sentimentNote: {
    zh: '这些是偏好而非硬性条件，AI会综合考虑',
    en: 'These are preferences, not hard filters',
    es: 'Son preferencias, no filtros estrictos',
  },
  volatilityRange: {
    zh: '波动率范围',
    en: 'Volatility Range',
    es: 'Rango de Volatilidad',
  },
  minAtr: { zh: '最低ATR%', en: 'Min ATR%', es: 'ATR% Mín.' },
  maxAtr: { zh: '最高ATR%', en: 'Max ATR%', es: 'ATR% Máx.' },
  customInstruction: {
    zh: 'AI自定义指令',
    en: 'Custom AI Instruction',
    es: 'Instrucción AI Personalizada',
  },
  customPlaceholder: {
    zh: '例：关注DeFi板块，避免meme币',
    en: 'e.g., Focus on DeFi sector, avoid meme coins',
    es: 'ej., Enfocarse en DeFi, evitar meme coins',
  },
  preview: {
    zh: '预览当前筛选结果',
    en: 'Preview Current Results',
    es: 'Vista Previa de Resultados',
  },
  volumeUnit: {
    zh: 'USDT (5000万 = 50000000)',
    en: 'USDT (50M = 50000000)',
    es: 'USDT (50M = 50000000)',
  },
  atrUnit: {
    zh: 'ATR14/价格×100, 1 = 1%波动',
    en: 'ATR14/Price×100, 1 = 1% volatility',
    es: 'ATR14/Precio×100, 1 = 1% volatilidad',
  },
  basicSettings: {
    zh: '基本设置',
    en: 'Basic Settings',
    es: 'Configuración Básica',
  },
  min: { zh: '最低', en: 'Min', es: 'Mín.' },
  max: { zh: '最高', en: 'Max', es: 'Máx.' },
  previewLoading: { zh: '加载中...', en: 'Loading...', es: 'Cargando...' },
  previewEmpty: {
    zh: '无匹配结果',
    en: 'No matching results',
    es: 'Sin resultados',
  },
  previewSymbol: { zh: '币种', en: 'Symbol', es: 'Símbolo' },
  previewVolume: { zh: '24h成交额', en: '24h Volume', es: 'Volumen 24h' },
  previewOI: { zh: '持仓量', en: 'Open Interest', es: 'Interés Abierto' },
  previewChange: { zh: '24h涨跌', en: '24h Change', es: 'Cambio 24h' },
}

// ============================================================================
// GRID CONFIG TRANSLATIONS (60+ keys)
// ============================================================================
export const gridConfig = {
  tradingPair: {
    zh: '交易设置',
    en: 'Trading Setup',
    es: 'Configuración de Trading',
  },
  gridParameters: {
    zh: '网格参数',
    en: 'Grid Parameters',
    es: 'Parámetros de Grid',
  },
  priceBounds: { zh: '价格边界', en: 'Price Bounds', es: 'Límites de Precio' },
  riskControl: { zh: '风险控制', en: 'Risk Control', es: 'Control de Riesgo' },
  symbol: { zh: '交易对', en: 'Trading Pair', es: 'Par de Trading' },
  symbolDesc: {
    zh: '选择要进行网格交易的交易对',
    en: 'Select trading pair for grid trading',
    es: 'Seleccionar par para grid trading',
  },
  totalInvestment: {
    zh: '投资金额 (USDT)',
    en: 'Investment (USDT)',
    es: 'Inversión (USDT)',
  },
  totalInvestmentDesc: {
    zh: '网格策略的总投资金额',
    en: 'Total investment for grid strategy',
    es: 'Inversión total',
  },
  leverage: { zh: '杠杆倍数', en: 'Leverage', es: 'Apalancamiento' },
  leverageDesc: {
    zh: '交易使用的杠杆倍数 (1-5)',
    en: 'Leverage for trading (1-5)',
    es: 'Apalancamiento (1-5)',
  },
  gridCount: { zh: '网格数量', en: 'Grid Count', es: 'Cantidad de Grids' },
  gridCountDesc: {
    zh: '网格层级数量 (5-50)',
    en: 'Number of grid levels (5-50)',
    es: 'Niveles (5-50)',
  },
  distribution: { zh: '资金分配方式', en: 'Distribution', es: 'Distribución' },
  distributionDesc: {
    zh: '网格层级的资金分配方式',
    en: 'Fund allocation across grid levels',
    es: 'Asignación de fondos',
  },
  uniform: { zh: '均匀分配', en: 'Uniform', es: 'Uniforme' },
  gaussian: {
    zh: '高斯分配 (推荐)',
    en: 'Gaussian (Recommended)',
    es: 'Gaussiana (Recomendado)',
  },
  pyramid: { zh: '金字塔分配', en: 'Pyramid', es: 'Pirámide' },
  useAtrBounds: {
    zh: '自动计算边界 (ATR)',
    en: 'Auto-calculate Bounds (ATR)',
    es: 'Calcular Límites (ATR)',
  },
  useAtrBoundsDesc: {
    zh: '基于 ATR 自动计算网格上下边界',
    en: 'Auto-calculate bounds based on ATR',
    es: 'Calcular límites automáticamente',
  },
  atrMultiplier: {
    zh: 'ATR 倍数',
    en: 'ATR Multiplier',
    es: 'Multiplicador ATR',
  },
  atrMultiplierDesc: {
    zh: '边界距离当前价格的 ATR 倍数',
    en: 'ATR multiplier for bounds distance',
    es: 'Distancia en ATR',
  },
  upperPrice: { zh: '上边界价格', en: 'Upper Price', es: 'Precio Superior' },
  upperPriceDesc: {
    zh: '网格上边界价格 (0=自动计算)',
    en: 'Grid upper bound (0=auto)',
    es: 'Límite superior (0=auto)',
  },
  lowerPrice: { zh: '下边界价格', en: 'Lower Price', es: 'Precio Inferior' },
  lowerPriceDesc: {
    zh: '网格下边界价格 (0=自动计算)',
    en: 'Grid lower bound (0=auto)',
    es: 'Límite inferior (0=auto)',
  },
  maxDrawdown: {
    zh: '最大回撤 (%)',
    en: 'Max Drawdown (%)',
    es: 'Máximo Drawdown (%)',
  },
  maxDrawdownDesc: {
    zh: '触发紧急退出的最大回撤百分比',
    en: 'Max drawdown before emergency exit',
    es: 'Drawdown máximo',
  },
  stopLoss: { zh: '止损 (%)', en: 'Stop Loss (%)', es: 'Stop Loss (%)' },
  stopLossDesc: {
    zh: '单仓位止损百分比',
    en: 'Stop loss per position',
    es: 'Stop loss por posición',
  },
  dailyLossLimit: {
    zh: '日损失限制 (%)',
    en: 'Daily Loss Limit (%)',
    es: 'Límite Diario (%)',
  },
  dailyLossLimitDesc: {
    zh: '每日最大亏损百分比',
    en: 'Maximum daily loss percentage',
    es: 'Pérdida diaria máxima',
  },
  useMakerOnly: {
    zh: '仅使用 Maker 订单',
    en: 'Maker Only Orders',
    es: 'Solo Maker',
  },
  useMakerOnlyDesc: {
    zh: '使用限价单以降低手续费',
    en: 'Use limit orders for lower fees',
    es: 'Órdenes límite para menos fees',
  },
  directionAdjust: {
    zh: '方向自动调整',
    en: 'Direction Auto-Adjust',
    es: 'Ajuste Automático de Dirección',
  },
  enableDirectionAdjust: {
    zh: '启用方向调整',
    en: 'Enable Direction Adjust',
    es: 'Habilitar Ajuste',
  },
  enableDirectionAdjustDesc: {
    zh: '根据箱体突破自动调整网格方向',
    en: 'Auto-adjust grid direction based on box breakouts',
    es: 'Ajustar según breaks',
  },
  directionBiasRatio: {
    zh: '偏向强度',
    en: 'Bias Strength',
    es: 'Intensidad de Sesgo',
  },
  directionBiasRatioDesc: {
    zh: '偏多/偏空模式的强度',
    en: 'Strength for long_bias/short_bias modes',
    es: 'Fuerza del sesgo',
  },
  directionBiasExplain: {
    zh: '偏多模式：X%买 + (100-X)%卖 | 偏空模式：(100-X)%买 + X%卖',
    en: 'Long bias: X% buy + (100-X)% sell | Short bias: (100-X)% buy + X% sell',
    es: 'Sesgo largo: X% compra | Sesgo corto: X% venta',
  },
  directionExplain: {
    zh: '短期箱体突破 → 偏向，中期箱体突破 → 全仓，价格回归 → 逐步恢复中性',
    en: 'Short box breakout → bias, Mid box breakout → full, Price return → gradually recover to neutral',
    es: 'Break corto → sesgo, Break medio → full',
  },
  directionModes: {
    zh: '方向模式说明',
    en: 'Direction Modes',
    es: 'Descripción de Modos',
  },
  modeNeutral: {
    zh: '中性：50%买 + 50%卖（默认）',
    en: 'Neutral: 50% buy + 50% sell (default)',
    es: 'Neutral: 50% compra + 50% venta',
  },
  modeLongBias: {
    zh: '偏多：X%买 + (100-X)%卖',
    en: 'Long Bias: X% buy + (100-X)% sell',
    es: 'Sesgo Largo: X% compra',
  },
  modeLong: {
    zh: '全多：100%买 + 0%卖',
    en: 'Long: 100% buy + 0% sell',
    es: 'Largo: 100% compra',
  },
  modeShortBias: {
    zh: '偏空：(100-X)%买 + X%卖',
    en: 'Short Bias: (100-X)% buy + X% sell',
    es: 'Sesgo Corto: X% venta',
  },
  modeShort: {
    zh: '全空：0%买 + 100%卖',
    en: 'Short: 0% buy + 100% sell',
    es: 'Corto: 100% venta',
  },
  buy: { zh: '买', en: 'buy', es: 'compra' },
  sell: { zh: '卖', en: 'sell', es: 'venta' },
}

// ============================================================================
// GRID RISK TRANSLATIONS (50 keys)
// ============================================================================
export const gridRisk = {
  gridRisk: { zh: '网格风控', en: 'Grid Risk', es: 'Riesgo de Grid' },
  leverageInfo: { zh: '杠杆', en: 'Leverage', es: 'Apalancamiento' },
  positionInfo: { zh: '仓位', en: 'Position', es: 'Posición' },
  liquidationInfo: { zh: '清算', en: 'Liquidation', es: 'Liquidación' },
  marketState: { zh: '市场', en: 'Market', es: 'Mercado' },
  boxState: { zh: '箱体', en: 'Box', es: 'Caja' },
  currentLeverage: { zh: '当前', en: 'Current', es: 'Actual' },
  effectiveLeverage: { zh: '有效', en: 'Effective', es: 'Efectivo' },
  recommendedLeverage: { zh: '建议', en: 'Recommend', es: 'Recomendado' },
  currentPosition: { zh: '当前', en: 'Current', es: 'Actual' },
  maxPosition: { zh: '最大', en: 'Max', es: 'Máximo' },
  positionPercent: { zh: '占比', en: 'Usage', es: 'Uso' },
  liquidationPrice: { zh: '清算价', en: 'Liq Price', es: 'Precio Liquidación' },
  liquidationDistance: { zh: '距离', en: 'Distance', es: 'Distancia' },
  regimeLevel: { zh: '波动', en: 'Regime', es: 'Regulación' },
  currentPrice: { zh: '价格', en: 'Price', es: 'Precio' },
  breakoutLevel: { zh: '突破', en: 'Breakout', es: 'Breakout' },
  breakoutDirection: { zh: '方向', en: 'Direction', es: 'Dirección' },
  shortBox: { zh: '短期', en: 'Short', es: 'Corto' },
  midBox: { zh: '中期', en: 'Mid', es: 'Medio' },
  longBox: { zh: '长期', en: 'Long', es: 'Largo' },
  narrow: { zh: '窄幅', en: 'Narrow', es: 'Estrecho' },
  standard: { zh: '标准', en: 'Standard', es: 'Estándar' },
  wide: { zh: '宽幅', en: 'Wide', es: 'Ancho' },
  volatile: { zh: '剧烈', en: 'Volatile', es: 'Volátil' },
  trending: { zh: '趋势', en: 'Trending', es: 'Tendencia' },
  none: { zh: '无', en: 'None', es: 'Ninguno' },
  short: { zh: '短期', en: 'Short', es: 'Corto' },
  mid: { zh: '中期', en: 'Mid', es: 'Medio' },
  long: { zh: '长期', en: 'Long', es: 'Largo' },
  up: { zh: '↑', en: '↑', es: '↑' },
  down: { zh: '↓', en: '↓', es: '↓' },
  loading: { zh: '加载中...', en: 'Loading...', es: 'Cargando...' },
  error: { zh: '加载失败', en: 'Load Failed', es: 'Error al Cargar' },
  noData: { zh: '暂无数据', en: 'No Data', es: 'Sin Datos' },
}

// ============================================================================
// RISK CONTROL TRANSLATIONS (25+ keys)
// ============================================================================
export const riskControl = {
  positionLimits: {
    zh: '仓位限制',
    en: 'Position Limits',
    es: 'Límites de Posición',
  },
  maxPositions: {
    zh: '最大持仓数量',
    en: 'Max Positions',
    es: 'Máximo de Posiciones',
  },
  maxPositionsDesc: {
    zh: '同时持有的最大币种数量',
    en: 'Maximum coins held simultaneously',
    es: 'Monedas máximas simultáneas',
  },
  tradingLeverage: {
    zh: '交易杠杆（交易所杠杆）',
    en: 'Trading Leverage (Exchange)',
    es: 'Apalancamiento (Exchange)',
  },
  btcEthLeverage: {
    zh: 'BTC/ETH 交易杠杆',
    en: 'BTC/ETH Trading Leverage',
    es: 'BTC/ETH Apalancamiento',
  },
  btcEthLeverageDesc: {
    zh: '交易所开仓使用的杠杆倍数',
    en: 'Exchange leverage for opening positions',
    es: 'Apalancamiento del exchange',
  },
  altcoinLeverage: {
    zh: '山寨币交易杠杆',
    en: 'Altcoin Trading Leverage',
    es: 'Apalancamiento Altcoins',
  },
  altcoinLeverageDesc: {
    zh: '交易所开仓使用的杠杆倍数',
    en: 'Exchange leverage for opening positions',
    es: 'Apalancamiento del exchange',
  },
  positionValueRatio: {
    zh: '仓位价值比例（代码强制）',
    en: 'Position Value Ratio (CODE ENFORCED)',
    es: 'Ratio de Valor (CÓDIGO)',
  },
  positionValueRatioDesc: {
    zh: '单仓位名义价值 / 账户净值，由代码强制执行',
    en: 'Position notional value / equity, enforced by code',
    es: 'Valor nominal / equity',
  },
  btcEthPositionValueRatio: {
    zh: 'BTC/ETH 仓位价值比例',
    en: 'BTC/ETH Position Value Ratio',
    es: 'BTC/ETH Ratio de Valor',
  },
  btcEthPositionValueRatioDesc: {
    zh: '单仓最大名义价值 = 净值 × 此值（代码强制）',
    en: 'Max position value = equity × this ratio (CODE ENFORCED)',
    es: 'Valor máximo = equity × ratio',
  },
  altcoinPositionValueRatio: {
    zh: '山寨币仓位价值比例',
    en: 'Altcoin Position Value Ratio',
    es: 'Altcoin Ratio de Valor',
  },
  altcoinPositionValueRatioDesc: {
    zh: '单仓最大名义价值 = 净值 × 此值（代码强制）',
    en: 'Max position value = equity × this ratio (CODE ENFORCED)',
    es: 'Valor máximo = equity × ratio',
  },
  riskParameters: {
    zh: '风险参数',
    en: 'Risk Parameters',
    es: 'Parámetros de Riesgo',
  },
  minRiskReward: {
    zh: '最小风险回报比',
    en: 'Min Risk/Reward Ratio',
    es: 'Ratio Riesgo/Recompensa Mínimo',
  },
  minRiskRewardDesc: {
    zh: '开仓要求的最低盈亏比',
    en: 'Minimum profit ratio for entry',
    es: 'Ratio mínimo para entrada',
  },
  maxMarginUsage: {
    zh: '最大保证金使用率（代码强制）',
    en: 'Max Margin Usage (CODE ENFORCED)',
    es: 'Uso Máximo de Margen (CÓDIGO)',
  },
  maxMarginUsageDesc: {
    zh: '保证金使用率上限，由代码强制执行',
    en: 'Maximum margin utilization, enforced by code',
    es: 'Límite de margen',
  },
  entryRequirements: {
    zh: '开仓要求',
    en: 'Entry Requirements',
    es: 'Requisitos de Entrada',
  },
  minPositionSize: {
    zh: '最小开仓金额',
    en: 'Min Position Size',
    es: 'Tamaño Mínimo',
  },
  minPositionSizeDesc: {
    zh: 'USDT 最小名义价值',
    en: 'Minimum notional value in USDT',
    es: 'Valor mínimo en USDT',
  },
  minConfidence: {
    zh: '最小信心度',
    en: 'Min Confidence',
    es: 'Confianza Mínima',
  },
  minConfidenceDesc: {
    zh: 'AI 开仓信心度阈值',
    en: 'AI confidence threshold for entry',
    es: 'Umbral de confianza AI',
  },
  executionConstraints: {
    zh: '执行约束',
    en: 'Execution Constraints',
    es: 'Restricciones de Ejecución',
  },
  binanceUsdcMaker: {
    zh: 'Binance USDC 挂单模式',
    en: 'Binance USDC Maker Mode',
    es: 'Modo Maker USDC de Binance',
  },
  binanceUsdcMakerDesc: {
    zh: '仅 Binance：有 USDC 永续的币自动改用 USDC 交易对（挂单0手续费），止盈改为 post-only 挂单成交。行情与内部记录仍用 USDT。需账户开启多资产模式或持有 USDC 保证金。默认对 Binance 开启。',
    en: 'Binance only: route bases with a USDC perp to USDC pairs (zero maker fee) and place take-profit as post-only maker orders. Market data and internal records stay USDT. Requires multi-asset mode or USDC margin. On by default for Binance.',
    es: 'Solo Binance: enruta a pares USDC (comisión maker cero) y coloca take-profit como órdenes maker post-only. Requiere modo multi-activo o margen USDC. Activado por defecto para Binance.',
  },
  entryCooldown: {
    zh: '止损后冷却 (分钟)',
    en: 'Post-loss cooldown (min)',
    es: 'Enfriamiento post-pérdida (min)',
  },
  entryCooldownDesc: {
    zh: '止损平仓后该币种禁止开仓的时间',
    en: 'Time before re-entry allowed after stop-loss',
    es: 'Tiempo antes de reentrada tras stop-loss',
  },
  maxEntryDeviation: {
    zh: '入场价偏差上限 %',
    en: 'Max entry deviation %',
    es: 'Desviación máx. de entrada %',
  },
  maxEntryDeviationDesc: {
    zh: 'AI 计划价与实际执行价的最大允许偏差',
    en: 'Max allowed gap between AI planned price and execution price',
    es: 'Brecha máx. entre precio AI y ejecución',
  },
  riskSizing: {
    zh: '风险反算仓位',
    en: 'Risk-based sizing',
    es: 'Tamaño basado en riesgo',
  },
  riskSizingDesc: {
    zh: '开启后，按止损距离反算仓位，使单笔最大亏损不超过权益的设定百分比（取 AI 止损与结构止损的较宽者）。仓位过小低于最小可执行值时自动跳过该单。',
    en: 'When on, position size is reverse-computed from the stop distance so a single trade loses at most the set % of equity (uses the WIDER of AI stop and structural stop). Trades whose size falls below the executable floor are skipped.',
    es: 'Cuando está activo, el tamaño se calcula desde la distancia del stop para que una operación pierda como máximo el % de capital fijado.',
  },
  riskPerTradePct: {
    zh: '单笔风险占权益 %',
    en: 'Risk per trade (% of equity)',
    es: 'Riesgo por operación (% del capital)',
  },
  riskPerTradePctDesc: {
    zh: '单笔交易允许的最大亏损占账户权益的百分比，例如 3 = 最多亏 3%',
    en: 'Max loss a single trade may incur as a % of account equity, e.g. 3 = at most 3%',
    es: 'Pérdida máxima de una operación como % del capital, p. ej. 3 = máx. 3%',
  },
  sessionPreOpen: {
    zh: '开盘前禁止开仓（股票/商品）',
    en: 'Block opens pre-market (stocks/commodities)',
    es: 'Bloquear aperturas pre-mercado (acciones/materias primas)',
  },
  sessionPreOpenDesc: {
    zh: '代币化股票/商品在其对应现货市场开盘前的敏感窗口内禁止新开仓（跳空风险最大时段）。加密货币不受影响，平仓和已有持仓保护不受影响。',
    en: 'Forbid opening new positions in tokenized stock/commodity symbols during the window before their underlying cash market opens (max overnight-gap risk). Crypto is unaffected; exits and existing-position protection are never gated.',
    es: 'Prohibir abrir nuevas posiciones en acciones/materias primas tokenizadas durante la ventana previa a la apertura del mercado subyacente. Las criptos no se ven afectadas.',
  },
  sessionPreOpenWindow: {
    zh: '开盘前窗口时长',
    en: 'Pre-open window length',
    es: 'Duración de la ventana pre-apertura',
  },
  sessionPreOpenWindowDesc: {
    zh: '开盘前多少分钟内禁止开仓，默认 60 分钟。',
    en: 'How many minutes before the cash-market open new opens are blocked. Default 60.',
    es: 'Cuántos minutos antes de la apertura se bloquean nuevas posiciones. Predeterminado 60.',
  },
}

// ============================================================================
// PROMPT SECTIONS TRANSLATIONS (12+ keys)
// ============================================================================
export const promptSections = {
  promptSections: {
    zh: 'System Prompt 自定义',
    en: 'System Prompt Customization',
    es: 'Personalización de Prompt',
  },
  promptSectionsDesc: {
    zh: '自定义 AI 行为和决策逻辑（输出格式和风控规则不可修改）',
    en: 'Customize AI behavior and decision logic (output format and risk rules are fixed)',
    es: 'Personalizar comportamiento AI',
  },
  roleDefinition: {
    zh: '角色定义',
    en: 'Role Definition',
    es: 'Definición de Rol',
  },
  roleDefinitionDesc: {
    zh: '定义 AI 的身份和核心目标',
    en: 'Define AI identity and core objectives',
    es: 'Definir identidad AI',
  },
  tradingFrequency: {
    zh: '交易频率',
    en: 'Trading Frequency',
    es: 'Frecuencia de Trading',
  },
  tradingFrequencyDesc: {
    zh: '设定交易频率预期和过度交易警告',
    en: 'Set trading frequency expectations and overtrading warnings',
    es: 'Establecer frecuencia',
  },
  entryStandards: {
    zh: '开仓标准',
    en: 'Entry Standards',
    es: 'Estándares de Entrada',
  },
  entryStandardsDesc: {
    zh: '定义开仓信号条件和避免事项',
    en: 'Define entry signal conditions and avoidances',
    es: 'Definir señales de entrada',
  },
  decisionProcess: {
    zh: '决策流程',
    en: 'Decision Process',
    es: 'Proceso de Decisión',
  },
  decisionProcessDesc: {
    zh: '设定决策步骤和思考流程',
    en: 'Set decision steps and thinking process',
    es: 'Establecer proceso',
  },
  resetToDefault: {
    zh: '重置为默认',
    en: 'Reset to Default',
    es: 'Restablecer',
  },
  chars: { zh: '字符', en: 'chars', es: 'caracteres' },
  modified: { zh: '已修改', en: 'Modified', es: 'Modificado' },
}

// ============================================================================
// INDICATOR TRANSLATIONS (75+ keys)
// ============================================================================
export const indicator = {
  marketData: { zh: '市场数据', en: 'Market Data', es: 'Datos de Mercado' },
  marketDataDesc: {
    zh: 'AI 分析所需的核心价格数据',
    en: 'Core price data for AI analysis',
    es: 'Datos de precio esenciales',
  },
  technicalIndicators: {
    zh: '技术指标',
    en: 'Technical Indicators',
    es: 'Indicadores Técnicos',
  },
  technicalIndicatorsDesc: {
    zh: '可选的技术分析指标，AI 可自行计算',
    en: 'Optional indicators, AI can calculate them',
    es: 'Indicadores opcionales',
  },
  marketSentiment: {
    zh: '市场情绪',
    en: 'Market Sentiment',
    es: 'Sentimiento de Mercado',
  },
  marketSentimentDesc: {
    zh: '持仓量、资金费率等市场情绪数据',
    en: 'OI, funding rate and market sentiment data',
    es: 'OI, funding rate',
  },
  quantData: { zh: '量化数据', en: 'Quant Data', es: 'Datos Quant' },
  quantDataDesc: {
    zh: '资金流向、大户动向',
    en: 'Netflow, whale movements',
    es: 'Netflow, ballenas',
  },
  timeframes: { zh: '时间周期', en: 'Timeframes', es: 'Marcos de Tiempo' },
  timeframesDesc: {
    zh: '选择 K 线分析周期，★ 为主周期（双击设置）',
    en: 'Select K-line timeframes, ★ = primary (double-click)',
    es: 'Seleccionar timeframes',
  },
  klineCount: { zh: 'K 线数量', en: 'K-line Count', es: 'Cantidad de Velas' },
  scalp: { zh: '超短', en: 'Scalp', es: 'Scalp' },
  intraday: { zh: '日内', en: 'Intraday', es: 'Intradía' },
  swing: { zh: '波段', en: 'Swing', es: 'Swing' },
  position: { zh: '趋势', en: 'Position', es: 'Posición' },
  rawKlines: {
    zh: 'OHLCV 原始 K 线',
    en: 'Raw OHLCV K-lines',
    es: 'Velas OHLCV',
  },
  rawKlinesDesc: {
    zh: '必须 - 开高低收量原始数据，AI 核心分析依据',
    en: 'Required - Open/High/Low/Close/Volume data for AI',
    es: 'Datos esenciales para AI',
  },
  required: { zh: '必须', en: 'Required', es: 'Requerido' },
  ema: { zh: 'EMA 均线', en: 'EMA', es: 'EMA' },
  emaDesc: {
    zh: '指数移动平均线',
    en: 'Exponential Moving Average',
    es: 'Media Móvil Exponencial',
  },
  macd: { zh: 'MACD', en: 'MACD', es: 'MACD' },
  macdDesc: {
    zh: '异同移动平均线',
    en: 'Moving Average Convergence Divergence',
    es: 'Convergencia/Divergencia',
  },
  rsi: { zh: 'RSI', en: 'RSI', es: 'RSI' },
  rsiDesc: {
    zh: '相对强弱指标',
    en: 'Relative Strength Index',
    es: 'Índice de Fuerza Relativa',
  },
  atr: { zh: 'ATR', en: 'ATR', es: 'ATR' },
  atrDesc: {
    zh: '真实波幅均值',
    en: 'Average True Range',
    es: 'Rango Promedio Verdadero',
  },
  boll: { zh: 'BOLL 布林带', en: 'Bollinger Bands', es: 'Bandas de Bollinger' },
  bollDesc: {
    zh: '布林带指标（上中下轨）',
    en: 'Upper/Middle/Lower Bands',
    es: 'Bandas Superior/Inferior',
  },
  volume: { zh: '成交量', en: 'Volume', es: 'Volumen' },
  volumeDesc: {
    zh: '交易量分析',
    en: 'Trading volume analysis',
    es: 'Análisis de volumen',
  },
  oi: { zh: '持仓量', en: 'Open Interest', es: 'Interés Abierto' },
  oiDesc: {
    zh: '合约未平仓量',
    en: 'Futures open interest',
    es: 'Posiciones abiertas',
  },
  fundingRate: { zh: '资金费率', en: 'Funding Rate', es: 'Funding Rate' },
  fundingRateDesc: {
    zh: '永续合约资金费率',
    en: 'Perpetual funding rate',
    es: 'Rate de perpetuo',
  },
  longShortRatio: {
    zh: '多空比',
    en: 'Long/Short Ratio',
    es: 'Ratio Long/Short',
  },
  longShortRatioDesc: {
    zh: '全市场多空账户比例',
    en: 'Market-wide long/short account ratio',
    es: 'Ratio de cuentas long/short',
  },
  topTraderRatio: {
    zh: '大户多空比',
    en: 'Top Trader L/S',
    es: 'Top Trader L/S',
  },
  topTraderRatioDesc: {
    zh: '大户持仓多空比 (仅Binance源)',
    en: 'Top trader position ratio (Binance only)',
    es: 'Ratio top traders (solo Binance)',
  },
  takerBuySellRatio: {
    zh: '主动买卖比',
    en: 'Taker Buy/Sell',
    es: 'Taker Compra/Venta',
  },
  takerBuySellRatioDesc: {
    zh: '主动买入/卖出量比',
    en: 'Taker buy vs sell volume ratio',
    es: 'Ratio volumen taker',
  },
  orderBookDepth: {
    zh: '盘口深度',
    en: 'Order Book Depth',
    es: 'Profundidad del Libro',
  },
  orderBookDepthDesc: {
    zh: '买卖盘深度失衡分析',
    en: 'Bid/ask depth imbalance analysis',
    es: 'Análisis de desequilibrio',
  },
  binanceOnly: { zh: '仅Binance源', en: 'Binance only', es: 'Solo Binance' },
  oiRanking: { zh: 'OI 排行', en: 'OI Ranking', es: 'Ranking OI' },
  oiRankingDesc: {
    zh: '持仓量增减排行',
    en: 'OI change ranking',
    es: 'Cambios de OI',
  },
  oiRankingNote: {
    zh: '显示持仓量增加/减少的币种排行，帮助发现资金流向',
    en: 'Shows coins with OI increase/decrease, helps identify capital flow',
    es: 'Identificar flujo de capital',
  },
  netflowRanking: { zh: '资金流向', en: 'NetFlow', es: 'Flujo de Fondos' },
  netflowRankingDesc: {
    zh: '机构/散户资金流向',
    en: 'Institution/retail fund flow',
    es: 'Institucional/Retail',
  },
  netflowRankingNote: {
    zh: '显示机构资金流入/流出排行，散户动向对比，发现聪明钱信号',
    en: 'Shows institution inflow/outflow ranking, retail flow comparison, Smart Money signals',
    es: 'Señales de Smart Money',
  },
  priceRanking: {
    zh: '涨跌幅排行',
    en: 'Price Ranking',
    es: 'Ranking de Precios',
  },
  priceRankingDesc: {
    zh: '涨跌幅排行榜',
    en: 'Gainers/losers ranking',
    es: 'Ganadores/Perdedores',
  },
  priceRankingNote: {
    zh: '显示涨幅/跌幅排行，结合资金流和持仓变化分析趋势强度',
    en: 'Shows top gainers/losers, combined with fund flow and OI for trend analysis',
    es: 'Analizar fuerza de tendencia',
  },
  priceRankingMulti: { zh: '多周期', en: 'Multi-period', es: 'Multi-período' },
  duration: { zh: '周期', en: 'Duration', es: 'Duración' },
  limit: { zh: '数量', en: 'Limit', es: 'Límite' },
  aiCanCalculate: {
    zh: '💡 提示：AI 可自行计算这些指标，开启可减少 AI 计算量',
    en: '💡 Tip: AI can calculate these, enabling reduces AI workload',
    es: '💡 AI puede calcularlos',
  },
  nofxosTitle: {
    zh: 'NofxOS 量化数据源',
    en: 'NofxOS Data Provider',
    es: 'Proveedor NofxOS',
  },
  nofxosDesc: {
    zh: '专业加密货币量化数据服务',
    en: 'Professional crypto quant data service',
    es: 'Servicio crypto quant',
  },
  nofxosFeatures: {
    zh: 'AI500 · OI排行 · 资金流向 · 涨跌榜',
    en: 'AI500 · OI Ranking · Fund Flow · Price Ranking',
    es: 'AI500 · OI · NetFlow · Ranking',
  },
  viewApiDocs: { zh: 'API 文档', en: 'API Docs', es: 'Docs API' },
  apiKey: { zh: 'API Key', en: 'API Key', es: 'API Key' },
  apiKeyPlaceholder: {
    zh: '输入 NofxOS API Key',
    en: 'Enter NofxOS API Key',
    es: 'Ingresar API Key',
  },
  fillDefault: { zh: '填入默认', en: 'Fill Default', es: 'Llenar Default' },
  connected: { zh: '已配置', en: 'Configured', es: 'Configurado' },
  notConfigured: { zh: '未配置', en: 'Not Configured', es: 'No Configurado' },
  nofxosDataSources: {
    zh: 'NofxOS 数据源',
    en: 'NofxOS Data Sources',
    es: 'Fuentes NofxOS',
  },
  configureApiKey: {
    zh: '请配置 API Key 以启用 NofxOS 数据源',
    en: 'Please configure API Key to enable NofxOS data sources',
    es: 'Configure API Key para habilitar NofxOS',
  },
}

// ============================================================================
// PUBLISH SETTINGS TRANSLATIONS (8 keys)
// ============================================================================
export const publishSettings = {
  publishToMarket: {
    zh: '发布到策略市场',
    en: 'Publish to Market',
    es: 'Publicar al Mercado',
  },
  publishDesc: {
    zh: '策略将在市场公开展示，其他用户可发现并使用',
    en: 'Strategy will be publicly visible in the marketplace',
    es: 'Visible públicamente',
  },
  showConfig: { zh: '公开配置参数', en: 'Show Config', es: 'Mostrar Config' },
  showConfigDesc: {
    zh: '允许他人查看和复制详细配置',
    en: 'Allow others to view and clone config details',
    es: 'Permitir clonación',
  },
  private: { zh: '私有', en: 'PRIVATE', es: 'PRIVADO' },
  public: { zh: '公开', en: 'PUBLIC', es: 'PÚBLICO' },
  hidden: { zh: '隐藏', en: 'HIDDEN', es: 'OCULTO' },
  visible: { zh: '可见', en: 'VISIBLE', es: 'VISIBLE' },
}

// ============================================================================
// CHART TABS TRANSLATIONS (5 keys)
// ============================================================================
export const chartTabs = {
  crypto: { zh: '加密', en: 'Crypto', es: 'Cripto' },
  stocks: { zh: '美股', en: 'Stocks', es: 'Acciones' },
  forex: { zh: '外汇', en: 'Forex', es: 'Forex' },
  metals: { zh: '金属', en: 'Metals', es: 'Metales' },
  hyperliquid: { zh: 'HL', en: 'HL', es: 'HL' },
}

// ============================================================================
// PRE-ENTRY GATE TRANSLATIONS
// ============================================================================
export const preEntryGate = {
  title: { zh: '开仓门禁', en: 'Pre-Entry Gate' },
  gateFlow: {
    zh: '门禁流程：市场状态 → 结构化开仓 → AI信心 → 允许开仓',
    en: 'Gate Flow: Market State → Entry Structure → AI Confidence → Allow Open',
  },
  marketStateGate: { zh: '市场状态门禁', en: 'Market State Gate' },
  confidenceGate: { zh: '信心门禁', en: 'Confidence Gate' },
  policyMode: { zh: '策略控制模式', en: 'Policy Mode' },
  entryStructure: { zh: '开仓结构约束', en: 'Entry Structure' },
  strict: { zh: '严格模式', en: 'Strict Mode' },
  strictDesc: {
    zh: '不满足门禁条件时阻止开仓',
    en: 'Block opening when conditions not met',
  },
  auditOnly: { zh: '审计模式', en: 'Audit Mode' },
  auditOnlyDesc: {
    zh: '记录违规但不阻止开仓',
    en: 'Log violations but allow opening',
  },
  recommendOnly: { zh: '建议模式', en: 'Recommend Mode' },
  recommendOnlyDesc: {
    zh: '仅提示建议，不影响开仓',
    en: 'Show suggestions only',
  },
  fundingRateUnit: {
    zh: '绝对值, 0.01 = 每8h费率1%',
    en: 'Absolute value, 0.01 = 1% per 8h',
  },
  atrUnit: {
    zh: 'ATR14/价格×100, 3 = 波动率3%',
    en: 'ATR14/Price×100, 3 = 3% volatility',
  },
  confidenceUnit: {
    zh: '0-100, 越高要求越严格',
    en: '0-100, higher = stricter',
  },
  rrUnit: {
    zh: '例: 3 表示盈亏比至少 1:3',
    en: 'e.g., 3 means min 1:3 risk-reward',
  },
  mutualExclusion: {
    zh: '互斥说明：市场状态阻止开仓时，后续门禁不再评估',
    en: 'Note: If Market State blocks, subsequent gates are not evaluated',
  },
  hierarchy: {
    zh: '层级：市场状态（第一道）→ 结构化开仓（第二道）→ AI信心（第三道）',
    en: 'Hierarchy: Market State (1st) → Entry Structure (2nd) → AI Confidence (3rd)',
  },
  allowedRegimes: { zh: '允许的市场状态', en: 'Allowed Regimes' },
  blockHighFunding: { zh: '屏蔽高资金费率', en: 'Block high funding' },
  blockHighVolatility: { zh: '屏蔽高波动', en: 'Block high volatility' },
  blockLowVolatility: { zh: '屏蔽低波动', en: 'Block low volatility' },
  minAtrUnit: {
    zh: 'ATR14/价格×100, 0.3 = 波动率0.3%。低于此值手续费占比过高',
    en: 'ATR14/Price×100, 0.3 = 0.3% volatility. Below this, fees take an outsized share',
  },
  volatilityWindowInverted: {
    zh: '下限须小于上限，否则所有开仓都会被拒',
    en: 'Floor must be below the ceiling, otherwise every entry is rejected',
  },
  requireTrendAlignment: { zh: '要求趋势同向', en: 'Require trend alignment' },
  // Momentum Gate
  momentumGate: { zh: '币种动量门禁', en: 'Coin Momentum Gate' },
  momentumGateDesc: {
    zh: '过滤无方向动量（横盘）或动量耗尽（追高追低）的币种',
    en: 'Filter coins with no directional momentum (flat) or exhausted momentum (late entry)',
  },
  enableMomentumGate: { zh: '启用动量门禁', en: 'Enable Momentum Gate' },
  momentumStaleChg1h: { zh: '横盘阈值 1h (%)', en: 'Stale threshold 1h (%)' },
  momentumStaleChg4h: { zh: '横盘阈值 4h (%)', en: 'Stale threshold 4h (%)' },
  momentumExhaustedChg4h: {
    zh: '耗尽阈值 4h (%)',
    en: 'Exhausted threshold 4h (%)',
  },
  momentumCounterChg1h: {
    zh: '逆向阈值 1h (%)',
    en: 'Counter threshold 1h (%)',
  },
  momentumStaleDesc: {
    zh: '|chg1h| < 阈值 且 |chg4h| < 阈值 → 判定为横盘，拒绝开仓',
    en: '|chg1h| < threshold AND |chg4h| < threshold → stale, block entry',
  },
  momentumExhaustedDesc: {
    zh: '|chg4h| > 阈值 → 趋势末期，均值回归风险高',
    en: '|chg4h| > threshold → late trend, high mean-reversion risk',
  },
  momentumCounterDesc: {
    zh: '1h 动量与开仓方向相反超过阈值 → 逆势开仓，拒绝',
    en: '1h momentum opposes trade direction beyond threshold → fighting the tape',
  },
  momentumFadingChg4h: {
    zh: '动量衰减阈值 4h (%)',
    en: 'Fading threshold 4h (%)',
  },
  momentumFadingDesc: {
    zh: '|chg4h| > 阈值 且 1h 动量占比 <10% → 大涨/大跌后追单，拒绝',
    en: '|chg4h| > threshold AND 1h ratio <10% → chasing after big move, block',
  },
  maxSlDistancePct: { zh: '止损距离上限 (%)', en: 'Max SL Distance (%)' },
  maxSlDistanceDesc: {
    zh: '止损距离超过此百分比 → 结构太松散，拒绝开仓',
    en: 'SL distance exceeds this % → structure too loose, block entry',
  },
  maxFundingAbs: { zh: '资金费率绝对值上限', en: 'Max Funding Rate (abs)' },
  maxAtr14Pct: { zh: 'ATR14 波动率上限 %', en: 'Max ATR14 %' },
  minConfidence: { zh: 'AI信心门槛', en: 'AI Confidence Threshold' },
  minRiskReward: { zh: '最低盈亏比', en: 'Min Risk-Reward Ratio' },
  enableRegimeFilter: { zh: '启用开仓门禁', en: 'Enable Pre-Entry Gate' },
  enableEntryGate: {
    zh: '启用 ATR / 入场位置门禁',
    en: 'Enable ATR / Entry Position Gate',
  },
  // Group A: Volatility Gate
  volatilityGate: { zh: '波动率门禁', en: 'Volatility Gate' },
  volatilityGateDesc: {
    zh: '过滤波动率过低的币种，避免手续费吃掉利润',
    en: 'Filter low-volatility coins where fees eat profits',
  },
  volatilityGateExample: {
    zh: '例：ATR14=0.8% 的横盘币种会被拒绝开仓',
    en: 'e.g. ATR14=0.8% sideways coin will be rejected',
  },
  minAtr14Pct: { zh: '最小 ATR14 %', en: 'Min ATR14 %' },
  // Group B: Entry Precision
  entryPrecision: { zh: '入场精度', en: 'Entry Precision' },
  entryPrecisionDesc: {
    zh: '确保入场价格贴近关键结构位，不追高/追低',
    en: 'Ensure entry price is near key structure, no chasing',
  },
  entryPrecisionExample: {
    zh: '例：当前价距支撑位超过 0.6×ATR 或 1.5% 时拒绝做多',
    en: 'e.g. reject long if price is >0.6×ATR or >1.5% from support',
  },
  entryProximityAtr: { zh: '入场贴近 ATR 倍数', en: 'Entry proximity ATR x' },
  entryProximityMaxPct: { zh: '入场最大偏离 %', en: 'Max entry gap %' },
  // Group C: Stop Loss Quality
  stopQuality: { zh: '止损质量', en: 'Stop Loss Quality' },
  stopQualityDesc: {
    zh: '确保止损位有足够空间且锚定在结构位',
    en: 'Ensure stop has enough room and anchors to structure',
  },
  stopQualityExample: {
    zh: '例：止损距离 <0.4% 太窄容易被扫；止损应在 0.5×ATR 以外的结构位',
    en: 'e.g. <0.4% stop is too tight; stop should be >0.5×ATR beyond structure',
  },
  minRiskDistancePct: { zh: '最小止损距离 %', en: 'Min risk distance %' },
  minSlDistanceAtr: {
    zh: '最小SL距离 (ATR×)',
    en: 'Min SL distance (ATR×)',
  },
  invalidationAtr: {
    zh: '失效位结构 ATR 倍数',
    en: 'Invalidation structure ATR x',
  },
  volatilityBufferAtr: {
    zh: '波动保护容错 (ATR×)',
    en: 'Volatility buffer (ATR×)',
  },
  volatilityBufferDesc: {
    zh: '额外加宽SL的波动保护距离（ATR倍数）。0=最紧，1.5=最宽。后端自动加宽不足的SL。',
    en: 'Extra SL padding for volatility (ATR multiples). 0=tightest, 1.5=widest. Backend auto-widens tight SL.',
  },
  // Group D: Path Clarity
  pathClarity: { zh: '路径清晰度', en: 'Path Clarity' },
  pathClarityDesc: {
    zh: '入场到目标之间不能有太多阻力/支撑层阻挡',
    en: 'Not too many S/R levels blocking the path to target',
  },
  pathClarityExample: {
    zh: '例：做多时上方有 5 层阻力 → 拒绝（目标难以到达）',
    en: 'e.g. 5 resistance levels above → reject (target unreachable)',
  },
  maxBlockingLevels: { zh: '最多路径阻力/支撑层', en: 'Max blocking levels' },
  // Group E: Confidence & Direction
  confidenceDirection: {
    zh: '置信度 & 方向门禁',
    en: 'Confidence & Direction',
  },
  confidenceDirectionDesc: {
    zh: '特殊市场状态下的额外置信度/RR 要求',
    en: 'Extra confidence/RR requirements for special regimes',
  },
  confidenceDirectionExample: {
    zh: '例：非下跌趋势做空需 conf≥78；挤压行情需 conf≥80 且 RR≥2.5',
    en: 'e.g. short in non-downtrend needs conf≥78; squeeze needs conf≥80 & RR≥2.5',
  },
  shortNonDowntrendConf: {
    zh: '做空非下跌趋势最低置信度',
    en: 'Short non-downtrend min confidence',
  },
  squeezeMinConf: { zh: '挤压行情最低置信度', en: 'Squeeze min confidence' },
  squeezeMinRR: { zh: '挤压行情最低 RR', en: 'Squeeze min RR' },
  minRewardAtr: { zh: '最小TP距离 (ATR×)', en: 'Min TP distance (ATR×)' },
  maxTargetAtr: { zh: '最大TP距离 (ATR×)', en: 'Max TP distance (ATR×)' },
  maxTargetAtrDesc: {
    zh: '目标距离超过该 ATR 倍数则拦截：远目标够不着，全样本回测(781单,样本外验证)显示 >5×ATR 时期望收益转负、目标仅~12%达成。默认 5.0，设 0 关闭。',
    en: 'Reject entries whose first_target exceeds this ATR multiple: far targets are unreachable. Full-sample backtest (781 trades, OOS-validated) shows EV turns negative and targets hit only ~12% of the time beyond 5×ATR. Default 5.0, set 0 to disable.',
  },
  targetReachabilityMode: { zh: '远目标处理方式', en: 'Far-target handling' },
  targetReachabilityModeDesc: {
    zh: '当 first_target 超过最大TP距离时：「压缩(cap)」把目标改写到可达上限并重算RR、保留这笔交易(默认)；「拒绝(reject)」直接拦掉(旧行为)。回测174笔远目标单54%其实跑过≥1倍风险利润只是没到远目标就折返——压缩+早锁盈能救回大部分。全组合：拒绝+28.7% vs 压缩+37.0%。',
    en: 'When first_target exceeds the max TP distance: "cap" rewrites it to the reachable ceiling and recomputes RR, keeping the trade (default); "reject" hard-blocks it (legacy). Backtest of 174 far-target trades: 54% actually ran ≥1× risk in profit but reverted before the unreachable target — cap+early-lock recovers most of it. Full-portfolio: reject +28.7% vs cap +37.0%.',
  },
  realisticTargetRiskMul: {
    zh: '首档锁盈 (×风险)',
    en: 'First-lock tier (×risk)',
  },
  realisticTargetRiskMulDesc: {
    zh: '喂给AI的首个止盈/保本档位距离，按止损风险的倍数(默认0.8，更容易落袋——被拦的盈利单105/174能到0.8×风险 vs 94能到1.0×)。由最小回报(1.8×ATR)兜底，确保锁盈档不落进波动噪声带被扫出。',
    en: 'First take-profit / break-even tier distance fed to the AI, as a multiple of stop-risk (default 0.8, easier to bank — 105/174 blocked winners reach 0.8× risk vs 94 at 1.0×). Floored by min-reward (1.8× ATR) so the lock tier clears the noise band and is not scanned out.',
  },
  blockBreakoutRetest: {
    zh: '突破回踩形态降权',
    en: 'Down-weight breakout_retest',
  },
  blockBreakoutRetestDesc: {
    zh: '给 setup_type=breakout_retest（突破后回踩再进场）的开仓打一个重扣分（-40 分），大幅缩小仓位而不是直接拒单——高确信的这类单仍可小仓开出。为什么降权：入场质量研究（1190 笔平仓、滚动5折前进验证、改善概率 98.8%）显示这个形态在每个时段都净负（早 -11.5 / 中 -28.6 / 晚 -4.0）。默认开启。关闭则不扣分。',
    en: 'Apply a heavy score penalty (-40) to entries tagged setup_type=breakout_retest (enter on the pullback after a breakout), sharply shrinking size instead of rejecting — a high-conviction one can still open small. Why: an entry-quality study (1190 closes, rolling 5-fold walk-forward, P(improve)=98.8%) shows this setup is net-negative in every time third (early -11.5 / mid -28.6 / late -4.0). Default on; off = no penalty.',
  },
  maxNetRr: { zh: '最大净RR', en: 'Max net RR' },
  maxNetRrDesc: {
    zh: 'AI承诺的净风险回报超过该上限则拦截：过度承诺的远目标很少达成(胜率~52%)，是 MaxTP距离 在RR轴上的镜像。同一研究显示 net_rr>2.8 净负，剔除后净值+58.8。默认2.8，设 0 用默认，设负数关闭。',
    en: 'Reject entries whose AI-promised net risk/reward exceeds this ceiling: over-promised far targets are rarely hit (~52% win rate) — the RR-axis mirror of Max TP distance. Same study: net_rr>2.8 is net-negative, removing it adds +58.8. Default 2.8, 0 uses default, negative disables.',
  },
  correlatedAdverseThrottle: {
    zh: '相关性逆境节流',
    en: 'Correlated-adverse throttle',
  },
  correlatedAdverseThrottleDesc: {
    zh: '当本交易员自己近期已平仓单集中转亏(毒性/相关性逆境)时，暂停新开仓。完全因果(只读本次入场之前已完成的平仓，无未来函数)。【默认关闭，按需开启】：在63天实盘(1273笔)上是唯一样本外(holdout +6.5、bootstrap P>0=96%、留一交易员全正)为正的入场杠杆；但2022-2026多年15币代理策略回测未能证实其可推广(全样本-72.7、仅2/5年为正、参数面混乱翻号)。原因是其真实edge并非"亏损成簇"本身，而是"毒性窗口能否预测下一笔亏损"——实盘该条件提升+9.8pp、代理里≈0。该预测力依赖策略与时期，仅在63天实盘窗口观测到，故默认关闭，待实盘重新确认后再按交易员启用。',
    en: "Pause new entries when the trader's OWN recently closed positions cluster into losses (toxic/correlated-adverse regime). Fully causal — reads only closes finished before this entry, no look-ahead. [DEFAULT OFF, opt-in]: on the 63-day live data (1273 trades) it was the sole entry lever positive out-of-sample (holdout +6.5, bootstrap P>0=96%, positive in leave-one-trader-out); but a multi-year (2022-2026, 15-coin) proxy-strategy backtest did NOT confirm it generalises (full-sample -72.7, positive in only 2/5 years, chaotic sign-flipping parameter surface). Its real edge is not loss-clustering itself but whether a toxic window PREDICTS the next loss — +9.8pp conditional lift in live vs ~0 in the proxy. That predictive lift is strategy/period-specific and only observed in the 63-day live window, so it ships OFF by default; enable per-trader after the live lift is re-confirmed.",
  },
  throttleWindowHours: { zh: '节流窗口(小时)', en: 'Throttle window (hours)' },
  throttleWindowHoursDesc: {
    zh: '评估毒性的近期已平仓单回看窗口(小时)。默认12(最优验证值，整个12h邻域均为正)。',
    en: 'Trailing window of finished closes used to assess toxicity. Default 12 (best-validated; the whole 12h neighbourhood is positive).',
  },
  throttleMinCloses: { zh: '节流最少平仓数', en: 'Throttle min closes' },
  throttleMinClosesDesc: {
    zh: '窗口内至少需有多少笔已完成平仓，节流才可能触发(避免小样本误判)。默认3。',
    en: 'Minimum finished closes required in the window before the throttle may fire (avoids acting on tiny samples). Default 3.',
  },
  throttleLossRate: { zh: '节流亏损率阈值', en: 'Throttle loss-rate' },
  throttleLossRateDesc: {
    zh: '窗口内亏损率达到或超过该值即拦截新开仓。默认0.6(近期平仓中≥60%为亏损)。范围(0,1]。',
    en: 'Loss-rate in the window at/above which new entries are blocked. Default 0.6 (≥60% of recent closes were losers). Range (0,1].',
  },
  blockLongInHtfDowntrend: {
    zh: '拦截1h+4h确认下跌做多',
    en: 'Block long in 1h+4h downtrend',
  },
  blockLongInHtfDowntrendDesc: {
    zh: '当1h和4h均确认下跌趋势时禁止做多。真实2026数据：4h确认的下跌做多15单净-4.7%(真下跌)，1h单独下跌16单净+1.7%(牛市回踩)。多时间框架确认过滤真下跌，保留盈利回踩机会。默认启用。',
    en: 'Block open_long when both 1h and 4h confirm downtrend. Real 2026: 4h-confirmed down×LONG 15 trades -4.7% (true downtrend), 1h-only 16 trades +1.7% (bull-market dips). Multi-TF confirmation filters toxic downtrends while preserving profitable dip-buys. Default enabled.',
  },
  blockShortInHtfUptrend: {
    zh: '拦截1h+4h确认上涨做空',
    en: 'Block short in 1h+4h uptrend',
  },
  blockShortInHtfUptrendDesc: {
    zh: '当1h和4h均确认上涨趋势时禁止做空。真实2026数据：4h确认的上涨做空9单净-4.9%(真上涨)，1h单独上涨7单净+6.6%(熊市反弹)。牛市模拟：快牛上涨做空-970%，慢牛-328%。多时间框架门控拦截真上涨做空，保留盈利熊市反弹空单。默认启用。',
    en: 'Block open_short when both 1h and 4h confirm uptrend. Real 2026: 4h-confirmed up×SHORT 9 trades -4.9% (true uptrend), 1h-only 7 trades +6.6% (bear bounces). Bull sim: up×SHORT -970% in fast bulls, -328% in slow bulls. Multi-TF gate blocks toxic real-uptrend shorts while preserving profitable bear-bounce fades. Default enabled.',
  },

  // ── Refactored structure: stage headers + beginner-friendly copy ──
  howGateWorks: {
    zh: '开仓门禁怎么工作：一笔候选开仓要依次通过下面几关。"硬门"不满足直接拒单；"降分项"不拒单，而是累计扣分——分数越低仓位越小（≥75 满仓，60-75 线性降到 5 成，<60 降到 3 成）。下面每项都标了它是硬门还是降分。',
    en: 'How the gate works: a candidate entry passes through the stages below in order. A "hard gate" rejects the trade outright when unmet; a "score penalty" does not reject — it deducts points and shrinks size (≥75 full, 60-75 tapers to 50%, <60 → 30%). Each item below is labelled hard-gate or penalty.',
  },
  stageMarketAccess: {
    zh: '① 市场准入 · 这个币现在能不能碰',
    en: '① Market Access · can we touch this coin now',
  },
  stageEntryQuality: {
    zh: '② 入场质量 · 这个入场点好不好',
    en: '② Entry Quality · is this a good entry',
  },
  stageTradePacing: {
    zh: '③ 交易节奏 · 最近手风顺不顺',
    en: '③ Trade Pacing · are recent trades going well',
  },
  stageConfidence: {
    zh: '④ 信心与方向 · AI 有多确信',
    en: '④ Confidence & Direction · how sure is the AI',
  },
  stageExecPolicy: {
    zh: '⑤ 执行策略 · 门禁不满足时怎么办',
    en: '⑤ Execution Policy · what to do when a gate fails',
  },

  grpMarketState: { zh: '市场状态', en: 'Market Regime' },
  grpMarketStateDesc: {
    zh: '只在你勾选的市场状态、且资金费率/波动率不极端时才允许开仓。这是第一道硬门。',
    en: 'Only allow entries in the regimes you tick, and when funding/volatility are not extreme. First hard gate.',
  },
  grpTrendAlign: { zh: '趋势同向', en: 'Trend Alignment' },
  grpTrendAlignDesc: {
    zh: '要求开仓方向顺应更高周期趋势——下跌趋势里不做多、上涨趋势里不做空。硬门。',
    en: 'Require the entry direction to follow the higher-timeframe trend — no longs in a downtrend, no shorts in an uptrend. Hard gate.',
  },
  grpStopPlacement: { zh: '止损位置', en: 'Stop Placement' },
  grpStopPlacementDesc: {
    zh: '确保止损离入场有足够空间、锚在结构位上，别太窄被扫也别太松散。',
    en: 'Make sure the stop has room, anchors to structure, and is neither too tight (scanned out) nor too loose.',
  },
  grpRewardTarget: { zh: '盈亏比与目标', en: 'Reward & Target' },
  grpRewardTargetDesc: {
    zh: '控制止盈目标的远近与盈亏比：目标太远够不着、承诺 RR 过高都会被处理。',
    en: 'Control how far the target sits and the risk-reward: unreachable far targets and over-promised RR are handled here.',
  },
  grpSetupFilter: { zh: '形态筛选', en: 'Setup Filter' },
  grpSetupFilterDesc: {
    zh: '按开仓形态(setup_type)与市场结构的契合度调整仓位。基于回测把弱形态降权，但不一票否决。',
    en: 'Adjust size by how well the setup_type fits market structure. Backtest-driven down-weighting of weak setups, without an outright veto.',
  },
  softRegimeFit: { zh: '结构错配降权', en: 'Down-weight structure mismatch' },
  softRegimeFitDesc: {
    zh: '当开仓形态与当前市场结构/趋势不匹配时，不直接拒单，而是扣分降仓(-20 分)。高确信的逆结构单可小仓开出——把"结构契合"当作信心加权证据，而非一票否决。真失效/陷阱信号(假回踩、保护策略拒绝)仍是硬门。默认开启。',
    en: 'When the setup does not match the current structure/trend, do not reject — deduct score and shrink size (-20). A high-conviction counter-structure trade can still open small, treating structure fit as confidence-weighted evidence rather than a veto. Genuine invalidation/trap signals (fake retest, protection rejection) stay hard gates. Default on.',
  },
  grpCorrelatedThrottle: {
    zh: '相关性逆境节流',
    en: 'Correlated-adverse throttle',
  },
  grpStructuralAlignment: {
    zh: '结构方向对齐 (HH/HL)',
    en: 'Structural alignment (HH/HL)',
  },
  structuralAlignmentDesc: {
    zh: '要求主周期已形成与开仓方向一致的摆动结构序列(做多需HH+HL递升,做空需LH+LL递降)才允许开仓。本阶段其他检查都读AI自报的关键位,而AI在研究样本中有47%的交易漏报了阻挡位;此检查直接从K线计算摆动点。默认关闭,需按trader单独开启。代码默认值为 lb=3 / n=2 / pct=0。⚠ 下列验证结论来自 1h 主周期的样本,不可直接套用到其他周期。验证方式:把1839笔已开仓单与1144笔"被既有闸门拦下且日志留有入场价"的单子放进同一套中性规则(持有6小时、不设止损止盈)重新模拟,两个放行集才可比;并剔除保护方案缺陷类拦截(止损落在失效位内侧等),因为无止损模拟看不到这类缺陷。1h 上 lb=3/n=3/pct=0.05 结果:放行284笔,均值+0.323% vs 无闸门基线-0.034%,p=0.0080;三折前向滚动全正、三个月全正、多空双向全正、剔除最大贡献币仍为正、4个trader全部改善。真实PnL独立复核(7月,离场机制一致):全部876笔实盘合计-78.16,而闸门会放行的121笔合计+62.97、胜率69.4%、p=0.0084。⚠ 15m 主周期另行实测(369笔,同一套中性规则):n=2 整列无效(lb=3时-0.077,劣于基线-0.071),n=3 才出现正区间(lb=3~6 连续为正,lb=4/n=3 最稳,+0.260 且三折全正),n=4 相邻格翻转不可用;15m 上无任何参数达到统计显著,且反向规则的 t 值反而更高,故 15m 建议先用"仅审计"模式积累实盘证据。未消除疑点:最优参数随窗口漂移;TON一个币贡献35~66%的收益;market_state阶段无法评估(对照组全部已通过它);1h 开仓频率从约21笔/天降到约3.3笔/天,15m 从约9笔/天降到约1.2笔/天。',
    en: 'Require the primary timeframe to already show a swing sequence agreeing with the trade direction (HH+HL for long, LH+LL for short). Every other check in this stage reads AI-self-reported key levels, and the AI omitted blocking levels in 47% of the research sample; this one computes pivots from candles. Default OFF, enable per trader. Code defaults are lb=3 / n=2 / pct=0. ⚠ The validation below comes from a 1h-primary sample and does NOT transfer to other timeframes. Validation: 1839 opened trades plus 1144 "entry gate blocked" log lines that carry an entry price, all re-simulated under ONE neutral rule (hold 6h, no SL/TP) so the two pass-sets are comparable; protection-plan-defect blocks (stop inside the invalidation level, etc.) excluded because a no-stop simulation cannot see them. On 1h at lb=3/n=3/pct=0.05: 284 passed, +0.323% mean vs -0.034% no-gate baseline, p=0.0080; all 3 walk-forward folds positive, all 3 months positive, both directions positive, still positive after removing the largest-contributing coin, all 4 traders improved. Independent check on real PnL (July, comparable exit machinery): all 876 opened trades total -78.16 while the 121 the gate would pass total +62.97 at 69.4% win, p=0.0084. ⚠ Measured separately on a 15m primary (369 entries, same neutral rule): the whole n=2 column is useless (lb=3 gives -0.077 vs baseline -0.071), a positive region only appears at n=3 (lb=3..6 all positive, lb=4/n=3 the most stable at +0.260 with all 3 folds positive), and n=4 is unusable because adjacent cells flip sign. Nothing on 15m reaches statistical significance and the INVERTED rule scores a higher t-stat, so on 15m start in audit-only mode and accumulate live evidence first. Unresolved: best parameters drift by window; TON alone contributes 35-66% of the gain; market_state cannot be evaluated (every control trade already passed it); entry frequency drops from ~21/day to ~3.3/day on 1h and from ~9/day to ~1.2/day on 15m.',
  },
  structuralPivotLookback: {
    zh: '摆动点分形半宽',
    en: 'Pivot fractal half-width',
  },
  structuralPivotLookbackDesc: {
    zh: '一个摆动点必须是左右各N根K线范围内的极值。默认3。⚠ 按主周期分别看:【1h】lb=3 实测最优且结论明确:lb=2是噪声(最好格点p=0.08且三折互相矛盾),lb=4偏弱(只在高阈值下勉强显著),而lb=3从0到0.35的每一个阈值都显著。【15m】需配合 n=3 使用,此时 lb=3~6 连续为正,其中 lb=4 最稳(+0.260,三折全正);lb=8 转负。范围1-10。',
    en: 'A pivot must be the extreme of N bars either side. Default 3. ⚠ Read per timeframe. [1h] lb=3 is measured-optimal and the result is decisive: lb=2 is noise (best cell p=0.08, folds disagree), lb=4 is weaker (only marginally significant at high thresholds), while every lb=3 cell from 0 to 0.35 is significant. [15m] only useful together with n=3, where lb=3..6 are all positive and lb=4 is the most stable (+0.260, all 3 folds positive); lb=8 turns negative. Range 1-10.',
  },
  structuralSwingCount: {
    zh: '摆动序列长度',
    en: 'Swing sequence length',
  },
  structuralSwingCountDesc: {
    zh: '最近多少组高点/低点必须构成干净的单调序列。默认2。⚠ 该推荐值来自 1h 主周期,15m 上结论相反,按主周期分别看:【1h】n=2 是验证过的推荐值:11.5笔/天、涉及28个币种(最大贡献币占27%)、逐币留一最不利+0.180(基线-0.034)、三个月增量全正、7月真实PnL四个trader全部改善,样本外增量+0.272(p=0.0012);设3的取舍是7月真实PnL上它显著(p=0.0192,而n=2只有p=0.1442),但开仓频率降到4.5笔/天且单个币种(TON)贡献55%;设4样本会塌到不可用。【15m】n=2 整列无效甚至有害(lb=3 时 -0.077,劣于基线 -0.071),必须用 n=3 才出现正区间(lb=3~6 连续为正),n=4 因相邻格翻转不可用。范围2-6。',
    en: 'How many recent swing highs/lows must form a clean monotonic sequence. Default 2. ⚠ That recommendation comes from a 1h primary; on 15m the conclusion reverses, so read it per timeframe. [1h] n=2 is the validated recommendation: 11.5 entries/day across 28 coins (top contributor 27%), leave-one-coin-out worst case +0.180 against a -0.034 baseline, all 3 months positive, all 4 traders improved on real July PnL, out-of-sample increment +0.272 (p=0.0012). The trade-off for 3: it IS significant on real July PnL (p=0.0192, where 2 reaches only p=0.1442) but drops to 4.5 entries/day and leans 55% on one coin (TON). 4 collapses the sample. [15m] the whole n=2 column is useless or harmful (lb=3 gives -0.077 against a -0.071 baseline); n=3 is required for any positive region (lb=3..6 all positive) and n=4 is unusable because adjacent cells flip sign. Range 2-6.',
  },
  structuralMinBlockingPct: {
    zh: '前方阻挡位最小距离%',
    en: 'Min blocking-level distance %',
  },
  structuralMinBlockingPctDesc: {
    zh: '开仓方向前方最近的【实算】摆动阻挡位至少要有这么远(占入场价百分比)。【默认0,即只检查方向不检查距离,这是刻意的】。曾按0.05步长扫参选出0.05,复核后被否决:它比0好的那点(7月真实PnL +62.97 vs +62.85,121笔)是噪音,却换来「参数是调出来的」这个真实弱点;更关键的是样本外验证里调参格点会退化(0.05:样本内+0.392→样本外+0.323),而0不退化(+0.289→+0.321)。收益全部来自方向检查本身。调高会让均值看起来更好(0.6可达+0.923)但过不了月度与逐trader筛查。任何非0值都应视为未验证。',
    en: 'The nearest COMPUTED swing pivot ahead must be at least this far away (percent of entry). DEFAULT 0 = direction check only, and that is deliberate. A 0.05-step sweep picked 0.05 and the pick was rejected on review: it beats 0 by +62.97 vs +62.85 on 121 trades of real July PnL, which is noise, while buying a real weakness — the value is tuned. More decisively, the tuned cells DEGRADE out-of-sample (0.05: in-sample +0.392 → out-of-sample +0.323) while 0 holds (+0.289 → +0.321). The direction check carries the whole effect. Higher values look better on mean (0.6 reaches +0.923) but fail the monthly and per-trader screens. Treat any non-zero value as unvalidated.',
  },
  structuralAuditOnly: {
    zh: '仅观察不拦截',
    en: 'Audit only (log, do not block)',
  },
  structuralAuditOnlyDesc: {
    zh: '只记录本会被拦截的开仓而不真正拦截,用于在实盘上积累证据。不扣减闸门评分,因此观察模式不会悄悄缩小仓位。',
    en: 'Log entries that WOULD be blocked without blocking them, to accumulate live evidence. Deducts no gate score, so observation cannot quietly shrink position size.',
  },
}

// ============================================================================
// HELPER FUNCTION
// ============================================================================

export function ts(
  entry: { zh: string; en: string; [k: string]: string },
  lang: string
): string {
  return entry[lang] ?? entry.en ?? ''
}

// ============================================================================
// AGGREGATED EXPORTS FOR TRANSLATIONS.TS
// ============================================================================

export const zhStrategy = {
  ...Object.fromEntries(Object.entries(coinSource).map(([k, v]) => [k, v.zh])),
  ...Object.fromEntries(Object.entries(aiScreener).map(([k, v]) => [k, v.zh])),
  ...Object.fromEntries(Object.entries(gridConfig).map(([k, v]) => [k, v.zh])),
  ...Object.fromEntries(Object.entries(gridRisk).map(([k, v]) => [k, v.zh])),
  ...Object.fromEntries(Object.entries(riskControl).map(([k, v]) => [k, v.zh])),
  ...Object.fromEntries(
    Object.entries(promptSections).map(([k, v]) => [k, v.zh])
  ),
  ...Object.fromEntries(Object.entries(indicator).map(([k, v]) => [k, v.zh])),
  ...Object.fromEntries(
    Object.entries(publishSettings).map(([k, v]) => [k, v.zh])
  ),
  ...Object.fromEntries(Object.entries(chartTabs).map(([k, v]) => [k, v.zh])),
}

export const enStrategy = {
  ...Object.fromEntries(Object.entries(coinSource).map(([k, v]) => [k, v.en])),
  ...Object.fromEntries(Object.entries(aiScreener).map(([k, v]) => [k, v.en])),
  ...Object.fromEntries(Object.entries(gridConfig).map(([k, v]) => [k, v.en])),
  ...Object.fromEntries(Object.entries(gridRisk).map(([k, v]) => [k, v.en])),
  ...Object.fromEntries(Object.entries(riskControl).map(([k, v]) => [k, v.en])),
  ...Object.fromEntries(
    Object.entries(promptSections).map(([k, v]) => [k, v.en])
  ),
  ...Object.fromEntries(Object.entries(indicator).map(([k, v]) => [k, v.en])),
  ...Object.fromEntries(
    Object.entries(publishSettings).map(([k, v]) => [k, v.en])
  ),
  ...Object.fromEntries(Object.entries(chartTabs).map(([k, v]) => [k, v.en])),
}

export const esStrategy = {
  ...Object.fromEntries(Object.entries(coinSource).map(([k, v]) => [k, v.es])),
  ...Object.fromEntries(Object.entries(aiScreener).map(([k, v]) => [k, v.es])),
  ...Object.fromEntries(Object.entries(gridConfig).map(([k, v]) => [k, v.es])),
  ...Object.fromEntries(Object.entries(gridRisk).map(([k, v]) => [k, v.es])),
  ...Object.fromEntries(Object.entries(riskControl).map(([k, v]) => [k, v.es])),
  ...Object.fromEntries(
    Object.entries(promptSections).map(([k, v]) => [k, v.es])
  ),
  ...Object.fromEntries(Object.entries(indicator).map(([k, v]) => [k, v.es])),
  ...Object.fromEntries(
    Object.entries(publishSettings).map(([k, v]) => [k, v.es])
  ),
  ...Object.fromEntries(Object.entries(chartTabs).map(([k, v]) => [k, v.es])),
}
